# This file defines the contenttypes on the website. See the documentation for
# details: http://docs.bolt.cm/content#defining-contenttypes

# pages:
#     name: Pages
#     slug: pages
#     singular_name: Page
#     singular_slug: page
#     record_template: contenttypes/page.twig
#     listing_template: contenttypes/pages.twig
#     # description: Generic pages.
#     default_status: published
#     # taxonomy: [ tags ]
#     show_on_dashboard: false
#     searchable: false
#     # viewless: false
#     recordsperpage: 100
#     listing_records: 100
#     sort: title ASC
#     fields:
#         title:
#             type: text
#             required: true
#         slug:
#             type: slug
#             uses: title
#         template:
#             type: templateselect
#             filter: '*.twig'

snippets:
    name: Snippets
    slug: snippets
    singular_name: Snippet
    singular_slug: snippet
    # record_template: contenttypes/snippet.twig
    # listing_template: contenttypes/snippets.twig
    # description: Generic snippets.
    default_status: published
    # taxonomy: [ tags ]
    show_on_dashboard: false
    searchable: false
    # viewless: true
    recordsperpage: 100
    listing_records: 100
    sort: title ASC
    fields:
        title:
            type: text
            required: true
        slug:
            type: slug
            uses: title
        template:
            type: templateselect
            filter: '*.twig'
        body:
            type: html



# # The 'Showcases' is not particularly useful in most cases, but it does a good
# # job of showcasing most of the available fieldtypes. Feel free to delete it, or
# # copy some fields to your own contenttypes.
# # Since no templates are defined for this contenttype, the default record_template,
# # listing_template, and related settings are used from config.yml

# showcases:
#     name: Showcases
#     slug: showcases
#     singular_name: Showcase
#     singular_slug: showcase
#     fields:
#         title:
#             type: text
#             class: large
#             required: true
#             pattern: ".{2,255}" # see: http://html5pattern.com/
#             error: "The Title field is required, and must contain at least 2 characters"
#             group: Text
#         slug:
#             type: slug
#             uses: [ title ]
#         html:
#             type: html
#             height: 150px
#         textarea:
#             type: textarea
#             postfix: "<p><em>This is a plain text area. the contents will not be processed.</em></p>"
#         markdown:
#             type: markdown
#             postfix: "<p><em>This field gets parsed as <a href='https://help.github.com/articles/markdown-basics'>Markdown</a>, when rendered on the site.</em></p>"
#         geolocation:
#             type: geolocation
#             group: Media
#         video:
#             type: video
#         image:
#             type: image
#             attrib: title # Note: retrieve this in your template with {{ record.values.image.title }}
#             extensions: [ gif, jpg, png ]
#         imagelist:
#             type: imagelist
#         file:
#             type: file
#             group: files
#         filelist:
#             type: filelist
#         template:
#             type: templateselect
#             filter: '*.twig'
#         checkbox:
#             type: checkbox
#             label: "This is a checkbox"
#             group: other
#         datetime:
#             type: datetime
#             default: "2000-01-01"
#             variant: inline
#         date:
#             type: date
#             default: "first day of last month"
#             variant: inline
#         integerfield:
#             type: integer
#             index: true
#         floatfield:
#             type: float
#         selectfield:
#             type: select
#             values: [ none, foo, bar ]
#         multiselect:
#             type: select
#             values: [ A-tuin, Donatello, Rafael, Leonardo, Michelangelo, Koopa, Squirtle ]
#             multiple: true
#             postfix: "Select your favourite turtle(s)."
#         selectentry:
#             type: select
#             values: entries/id,title
#             postfix: "Select an entry"
#             autocomplete: true
#             sort: title
#     relations:
#         entries:
#             multiple: false
#             label: "Choose an entry"
#             order: -id
#             format: "{{ item.title|escape }} <span>(№ {{ item.id }})</span>"
#             postfix: "By selecting an Entry, you're creating a bi-directional relationship to that Entry."
#         pages:
#             multiple: true
#             order: title
#             label: Select zero or more pages
#     taxonomy: [ categories, tags ]
#     show_on_dashboard: true
#     default_status: publish
#     searchable: false
#     icon_many: "fa:cubes"
#     icon_one: "fa:cube"

# Using YAML repeated nodes
#
# YAML allows the defining of "repeated nodes". These allow you to define a 'node'
# with a 'key: &name' and referenced later with '<<: *name'
#
# Bolt allows you to define this with the special entry of '__nodes:' that itself 
# won't create a Contenttype, but will allow you to use it in actual contenttypes
# to prevent repeating yourself.
#
# To achieve this, first create a key '__nodes:' 
#__nodes:
#    field_defaults: &field_defaults
#        title:
#            type: text
#            class: large
#            group: main
#        slug:
#            type: slug
#            uses: title
#    template_defaults: &template_defaults
#        template:
#            type: templateselect
#            filter: '*.twig'
#            group: meta
#
# Then, as an example, you could create a Contenttype with default fields, with 
# an additional 'image' field.
#
#contenttype_abc:
#    name: Contenttype Abc
#    fields:
#        <<: *field_defaults
#        image:
#            type: image
#            attrib: title
#            extensions: [ gif, jpg, png ]
#        <<: *template_defaults
#    taxonomy: [ chapters ]
#    recordsperpage: 10
#
# Alternatively, or additionally, you then can thencreate a Contenttype with 
# default fields, and a 'select' field, and a different 'templateselect' option.
#
#contenttype_xyz:
#    name: Contenttype Xyz
#    fields:
#        <<: *field_defaults
#        selectfield:
#            type: select
#            values: [ none, foo, bar ]
#        template:
#            type: templateselect
#            filter: '*_xyz.twig'
#    taxonomy: [ tags ]
#    recordsperpage: 20

# Possible field types:
#
# text - varchar(256) - input type text.
# integer - integer - Input field for integer numbers.
# float - double - Input field for floating numbers, stored as 'Double'.
# geolocation - text (65kb) - Input field for geolocation. Enter an address, and the location is geocoded to latitude/longitude coordinates
# imagelist - text (65kb) - Input type for imagelists. Add multiple images with a description. Useful for image sliders, galleries, etcetera.
# image - varchar(256) - image select/upload widget, stored as filename.
# file - varchar(256) - file select/upload widget, stored as filename.
# filelist - text (65kb) - Input type for a list of files. Including a description.
# video - varchar(256) - Video embed widget, stored as filename.
# html - text (65kb) - wysiwyg element.
# textarea - varchar(32768) - Simple, plain < textarea > field.
# markdown - varchar(32768) - Simple, plain < textarea > field, which is parsed as Markdown text.
# datetime - datetime - date and time selector widget.
# date - datetime - date selector widget.
# select - varchar(256) - select with predefined values
# templateselect - varchar(256) - select with template filenames
# checkbox - integer - checkbox-field which is 1 (checked) or 0 (unchecked)

# number (deprecated) - input type decimal(18,9), useful for storing number that need to be sortable
