# This file defines the menus on the website. See the documentation for
# details: http://docs.bolt.cm/menus

main:
    - label: Home
    - label: All snippets
      path: snippets/
      # submenu:
      #     - label: Sub 1
      #       path: entry/2
      #     - label: Sub 2
      #       class: menu-item-class
      #       path: entry/3
      #     - label: Sub 3
      #       path: entry/4
      #     - label: Sub 4
      #       class: sub-class
      #       path: page/3
    - label: eiskis.net
      link: http://eiskis.net/
