# Config file for this default theme
# http://www.yaml.org/start.html

# Variables that are in this file, can be used in your twig template like {{ theme.foo }}
# Note: If variables do not immediately show up, clear the cache, in the Bolt Backend.
config:
    # locale: en_US    # Set in main config
    language: en
    services:
        googleanalytics:
            id: UA-12345678
        facebook:
            id: 1234567891234567
            url: https://www.facebook.com/facebookpagename
    assetlinks:
        css:
            external:
                - '//fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,700,300,600,800,400'
            internal:
                - public/all.min.css
        js:
            external:
                - //code.jquery.com/jquery-2.1.1.min.js
            internal:
                - public/all.min.js

# Template filenames. If you 're creating a theme for distribution, you can specify
# the filenames of the templates here. The templates you will set in this config
# file will override the ones in the global app/config/config.yml, so beware!
maintenance_template: twig/maintenance.twig
homepage_template: twig/contenttypes/page.twig
record_template: twig/record.twig
listing_template: twig/listing.twig
search_results_template: twig/search.twig

templatefields:
    extrafields.twig:
        section_1:
            type: text
            label: Section 1
        section_2:
            type: html
            label: Section 2
        image:
            type: image

# There can be defined the templates for the template chooser
#templateselect:
#    templates:
#        record:
#            name: 'Template for Records'
#            filename: 'record.twig'