#!/usr/bin/env bash

# Handle working directory
cd "$(dirname "$0")"
cd ..

# Deploy with Rocketeer. See config under .rocketeer/

# Target specified
if [ $1 ]; then
	php bin/rocketeer.phar deploy --on=$1

# Deploy to default
else
	php bin/rocketeer.phar deploy
fi
