#!/usr/bin/env bash

# Handle working directory
cd "$(dirname "$0")"
cd ..

# Download Composer binary
curl -sS https://getcomposer.org/installer | php -- --install-dir=bin

# Download Rocketeer binary
curl -o bin/rocketeer.phar http://rocketeer.autopergamene.eu/versions/rocketeer.phar
