#!/usr/bin/env bash

# Handle working directory
cd "$(dirname "$0")"
cd ..

# Install dependencies with Composer
php bin/composer.phar update
php bin/composer.phar update --working-dir="extensions/"

# Install node dependencies for theme
cd theme/base/
npm update
./node_modules/.bin/bower update
