# Config file for this default theme
# http://www.yaml.org/start.html

# setup.twig will put these into theme.config for use
copyfromappconfig:
    debug: debug
    locale: locale
    sitename: sitename
    sitedescription: payoff

# setup.twig will prefix and put these in the global paths section
paths:
    public: public/

# Pass stuff to JavaScript as global objects. Set each to false to disable.
passtojs:
    config: 'config'
    paths: 'paths'

# link to these files in HTML templates
# bower components are automatically linked
assetlinks:
    css:
        external:
            # - '//fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,700,300,600,800,400'
        internal:
            # - public/build/vendor.css
            - public/build/all.css
    js:
        external:
            - //code.jquery.com/jquery-2.1.1.min.js
        internal:
            - public/build/vendor.js
            - public/build/all.js

# Variables that are in this file, can be used in your twig template like {{ theme.foo }}
# Note: If variables do not immediately show up, clear the cache, in the Bolt Backend.
config:
    language: en
    services:
        googleanalytics:
            id: UA-12345678
        facebook:
            id: 1234567891234567
            username: username
        twitter:
            username: username
        linkedin:
            username: companyname

# Template filenames. If you 're creating a theme for distribution, you can specify
# the filenames of the templates here. The templates you will set in this config
# file will override the ones in the global app/config/config.yml, so beware!
homepage_template: twig/main/index.twig
listing_template: twig/main/records.twig
maintenance_template: twig/main/maintenance.twig
record_template: twig/main/record.twig
search_results_template: twig/main/search.twig

# Custom template fields
# templatefields:
#     twig/main/notfound.twig:
#         section_1:
#             type: text
#             label: Section 1
#         section_2:
#             type: html
#             label: Section 2
#         image:
#             type: image

# There can be defined the templates for the template chooser
# templateselect:
#    templates:
#        record:
#            name: 'Template for Records'
#            filename: 'twig/contenttypes.page.twig'
